Addition of filenames field in Posts types
mattermost/mattermost-redux pull request #1261
Opened 2020-10-15 20:07 UTC by vipul08

#### Summary

This Pull Request adds an additional field `filenames` in `Posts` types which is required in the below GitHub issue. With this addition, we will be able to remove compilation error in the `post_body.tsx` (migration from jsx to tsx).

#### Ticket Link

 Fixes https://github.com/mattermost/mattermost-server/issues/15440

2020-10-15 20:07 UTC, mattermod commented
Hello @vipul08,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-19 09:19 UTC, jespino approved these changes
Looks good to me. Thanks @vipul08! :tada:

2020-10-21 21:06 UTC, calebroseland requested changes
Just one minor request on extra spaces, but otherwise LGTM!

2020-10-21 21:06 UTC, calebroseland commented on src/types/posts.ts
> +    postsReplies: { [x in $ID<Post>]: number };
```suggestion
    postsReplies: {[x in $ID<Post>]: number};
```
nit: I don't think eslint/tsc checks for this in particular, but the normal convention (mattermost-webapp/redux) is no spaces around inline object notation 1/5

2020-10-22 05:27 UTC, vipul08 commented
@calebroseland - I have made changes as suggested. Kindly review.

2020-10-22 14:52 UTC, calebroseland approved these changes
Thanks!

2020-10-22 14:55 UTC, calebroseland commented
Nothing to QA (type-only)

2020-10-22 14:56 UTC, merged