Updated apps types to reflect server changes
mattermost/mattermost-redux pull request #1287
Opened 2020-11-07 21:18 UTC by levb

Matches https://github.com/mattermost/mattermost-plugin-apps/pull/32

2020-11-07 21:45 UTC, jfrerich approved these changes

2020-11-10 07:54 UTC, mickmister requested changes

2020-11-10 13:49 UTC, levb commented on src/selectors/entities/apps.ts
> +            return headerBindings.bindings!;
Please make it right... I was getting a TS lint error.

2020-11-11 00:04 UTC, mickmister commented on src/selectors/entities/apps.ts
> +            return headerBindings.bindings!;
It shows up elsewhere in the codebase. Puzzled by this, as the javascript output is identical, except there is no exclamation point. (also I apologize for seemingly yelling in my above comment)

2020-11-11 00:09 UTC, mickmister commented on src/selectors/entities/apps.ts
> +            return headerBindings.bindings!;
Circling back to this, what is the main benefit of having the bindings structured this way, as opposed to a flat list? The level of indirection here versus of the data flow from `server -> mattermost-redux -> mattermost-webapp` seems off. Why should the webapp expect to receive data that is not the same form that came from the server?

2020-11-11 00:29 UTC, mickmister approved these changes

2020-11-12 11:49 UTC, larkox approved these changes
LGTM, just one small question.

2020-11-12 11:49 UTC, larkox commented on src/constants/apps.ts
> +    APPS_BINDINGS_IN_POST: '/in_post',
Random idea: Are we considering more stuff to add "in_post" apart of embedded forms? I cannot think of any useful idea, but I still see potential.

2020-11-12 11:49 UTC, larkox commented on src/types/apps.ts
> -    COMMAND: 'command',
Are we dropping the possibility to run "any command"?

2020-11-17 02:11 UTC, merged