MM-32525 added unread_mentions_per_channel
mattermost/mattermost-redux pull request #1353
Opened 2021-02-04 12:42 UTC by reflog

#### Summary

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-32525

2021-02-04 22:21 UTC, calebroseland requested changes

2021-02-04 22:21 UTC, calebroseland commented on src/reducers/entities/threads.ts
> +                ...state[action.data.team_id]?.unread_mentions_per_channel ?? {},
```suggestion
                ...state[action.data.team_id] ?? {},
```

2021-02-04 22:21 UTC, calebroseland commented on src/types/threads.ts
> +        unread_mentions_per_channel: Record<string, number>;
`import type {Channel} from './channels';`
```suggestion
        unread_mentions_per_channel: Record<$ID<Channel>, number>;
```

2021-02-04 22:21 UTC, calebroseland commented on src/reducers/entities/threads.test.js
> +    test('RECEIVED_THREADSshould  update the state', () => {
```suggestion
    test('RECEIVED_THREADS should update the state', () => {
```

2021-02-04 22:21 UTC, calebroseland commented on src/client/client4.ts
> +        const url = `${this.getUserThreadsRoute(userId, teamId)}`;
```suggestion
        const url = `${this.getUserThreadsRoute(userId, teamId)}/mention_counts`;
```

2021-02-05 17:05 UTC, jespino approved these changes
LGTM, except for the @calebroseland comments.

2021-02-09 02:52 UTC, calebroseland approved these changes

2021-02-09 10:03 UTC, merged