Updated AppManifests
mattermost/mattermost-redux pull request #1426
Opened 2021-10-09 19:42 UTC by adithyaakrishna

Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

#### Summary
Updates AppManifests according to https://github.com/mattermost/mattermost-plugin-apps/blob/3518d938db7271362d55b53fda492facf0006210/apps/manifest.go#L22

#### Ticket Link
This PR is Related to https://github.com/mattermost/mattermost-app-zendesk/issues/78

2021-10-09 19:42 UTC, mattermod commented
Hello @adithyaakrishna,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-10-09 20:07 UTC, adithyaakrishna commented on src/types/apps.ts
> +  on_oauth2_complete?: AppBinding;
I wasn't sure completely about what data type to have for this, as the go file mentioned *Call I've added AppBinding here. Please do lmk if I need to change it to something else :)

2021-10-11 16:15 UTC, jfrerich requested changes
Thanks for the PR, @adithyaakrishna! 

I've left some notes for you. If it takes a while for this PR to get merged, I will change the issue to only create the Manifest Type in Redux and create a separate issue for importing into the Zendesk app.

2021-10-11 16:15 UTC, jfrerich commented on src/types/apps.ts
> +  on_oauth2_complete?: AppBinding;
The `Call` struct can be found here. https://github.com/adithyaakrishna/mattermost-redux/blob/master/src/types/apps.ts#L79-L83

2021-10-11 16:15 UTC, jfrerich commented on src/types/apps.ts
> +  on_oauth2_complete?: AppBinding;
The `kubeless_functions` and `aws_lambda` types are not yet defined in this file.  I'm ok with commenting those out if you would like or you can implement them to match the following go structs

https://github.com/mattermost/mattermost-plugin-apps/blob/3518d938db7271362d55b53fda492facf0006210/apps/manifest.go#L116

https://github.com/mattermost/mattermost-plugin-apps/blob/3518d938db7271362d55b53fda492facf0006210/apps/manifest.go#L178

2021-10-12 13:18 UTC, adithyaakrishna commented
Okay sure, I'll add the kubeless and aws types here as well :)

2021-10-12 13:28 UTC, adithyaakrishna commented
/check-cla

2021-10-12 16:23 UTC, mickmister commented on src/types/apps.ts
> +  on_oauth2_complete?: AppBinding;
@levb Are we at a stable enough spot with the manifest structure where we should be updating the types in this repo? I suppose it doesn't hurt to keep them in sync in general

2021-10-12 17:01 UTC, adithyaakrishna commented on src/types/apps.ts
> +  kubeless_functions?: string;
My Notes: Comment Them

2021-10-12 19:39 UTC, hmhealey commented
Thanks for the PR, @adithyaakrishna. Unfortunately, I think we might have run into some confusion over where this change should be happening.

@jfrerich We haven't been shipping mattermost-redux since it was moved out of this repo and into the web app. We could update it in the web app's version of mattermost-redux, but it won't be available to Apps wanting to use this type either way. Maybe we could look at shipping those types to Apps some other way since we're not in a state to ship mattermost-redux as a whole?

2021-10-12 19:40 UTC, hmhealey commented on src/types/apps.ts
> +  on_oauth2_complete?: AppBinding;
See my comment below. Even if the manifest structure is stable, we haven't been shipping mattermost-redux, so these new types won't be usable for any Apps wanting to import them. I'm happy to discuss what we might do here though

2021-10-12 19:47 UTC, adithyaakrishna commented
@hmhealey Gotcha, should I move this to the other Repo? 👀

2021-10-12 20:58 UTC, hmhealey commented
Yeah, that'd probably make sense, but that won't make them accessible for use in mattermost-app-zendesk, so we might want to wait to see what @jfrerich was intending with the ticket.

2021-10-15 22:19 UTC, mickmister commented
@hmhealey @jfrerich
As I mentioned [here](https://community-daily.mattermost.com/core/pl/xw5c6tw1s7n1tgcuabdk1utqbw), I'm proposing we move server-side relevant pieces of `mattermost-redux` to a separate repo. Either way we definitely need a way to continue updating types for Node.js applications going forward.

2021-10-23 12:37 UTC, adithyaakrishna commented
> @hmhealey @jfrerich As I mentioned [here](https://community-daily.mattermost.com/core/pl/xw5c6tw1s7n1tgcuabdk1utqbw), I'm proposing we move server-side relevant pieces of `mattermost-redux` to a separate repo. Either way we definitely need a way to continue updating types for Node.js applications going forward.

Gotcha @mickmister 💯 
Will close this and move it there :)

2021-11-03 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-11-04 15:05 UTC, hmhealey commented
Closing this in favour of the mattermost-webapp PR

2021-11-04 15:05 UTC, closed without merging